[package]
name = "fast-diff-mcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fast_diff_mcp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0" }
similar = "2.7.0"
